---

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Metrics/AbcSize:
  Max: 48
Metrics/BlockLength:
  Max: 250
Metrics/ClassLength:
  Max: 250
Metrics/MethodLength:
  Max: 50
Metrics/CyclomaticComplexity:
  Max: 16
Metrics/PerceivedComplexity:
  Max: 16

Layout/LineLength:
  Max: 180

Style/Documentation:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/OptionalBooleanParameter:
  Enabled: false
