---

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false

Layout/LineLength:
  Max: 180

Style/Documentation:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/OptionalBooleanParameter:
  Enabled: false
