---

AllCops:
  TargetRubyVersion: 2.3

Metrics/AbcSize:
  Max: 32
Metrics/LineLength:
  Max: 180
Metrics/BlockLength:
  Max: 250
Metrics/ClassLength:
  Max: 250
Metrics/MethodLength:
  Max: 50
Metrics/CyclomaticComplexity:
  Max: 16
Metrics/PerceivedComplexity:
  Max: 16

Style/Documentation:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false
